title : RIMEL UCA 
tagline: Reverse
author :
  name : Mireille Blay-Fornarino
  email : blay@unice.fr

permalink: /:year/:month/:day/:title.html
redirects: yes
exclude: [ _posts/source/, _posts/_private/ ]

gems:
  - jekyll-pandoc

markdown: pandoc
pandoc:
   extensions:
      - mathjax

highlighter: pygments
source: .
lsi: True

pageviews: yes    ## toggle on sidebar pageviews 
gitstamps: yes
repo: https://github.com/RIMEL-UCA/RIMEL-UCA.github.io # used in linking history

baseurl: '/'

#markdown: redcarpet
#redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
